// <auto-generated />
using System;
using ISB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISB.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20250317192519_docsss")]
    partial class docsss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISB.Models.Audit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditObjectives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditScope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Due_Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority_id")
                        .HasColumnType("int");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type_id")
                        .HasColumnType("int");

                    b.Property<int>("assignedauditor")
                        .HasColumnType("int");

                    b.Property<int>("project_id")
                        .HasColumnType("int");

                    b.Property<int>("task_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Priority_id");

                    b.HasIndex("Type_id");

                    b.HasIndex("assignedauditor");

                    b.HasIndex("project_id");

                    b.ToTable("tbl_audit");
                });

            modelBuilder.Entity("ISB.Models.AuditType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_auditTypes");
                });

            modelBuilder.Entity("ISB.Models.Audit_Conclusion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary_Findings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rating_id");

                    b.ToTable("tblaudit_Conclusions");
                });

            modelBuilder.Entity("ISB.Models.Audit_Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_auditRating");
                });

            modelBuilder.Entity("ISB.Models.BudgetAdherence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_bugetaherence");
                });

            modelBuilder.Entity("ISB.Models.Communication_Effectivenes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_CommunicationEffectiveness");
                });

            modelBuilder.Entity("ISB.Models.Companies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateCurrent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("user_invitations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_companies");
                });

            modelBuilder.Entity("ISB.Models.ComplianceStandards", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("compliacne_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("compliacne_id");

                    b.ToTable("tbl_complianceandStandards");
                });

            modelBuilder.Entity("ISB.Models.CorrectiveMeasures", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ImprovementSuggestions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("priority_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("priority_id");

                    b.ToTable("tbl_auditCorrectiveMeasures");
                });

            modelBuilder.Entity("ISB.Models.CorrectiveMeasures_priority", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_measurePrority");
                });

            modelBuilder.Entity("ISB.Models.Docs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Desciprtion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_docs");
                });

            modelBuilder.Entity("ISB.Models.Impact_risk", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("risk_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("scoring")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_impact_risk");
                });

            modelBuilder.Entity("ISB.Models.IssueSeverity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_issueSeverity");
                });

            modelBuilder.Entity("ISB.Models.Issues_Challenges", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Issue_Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Open_Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_issue");
                });

            modelBuilder.Entity("ISB.Models.Likelihood_risk", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("risk_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("scoring")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_likedhood_risk");
                });

            modelBuilder.Entity("ISB.Models.ResolutionStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_ResolutionStatus");
                });

            modelBuilder.Entity("ISB.Models.ScheduleAdherence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_ScheduleAdherence");
                });

            modelBuilder.Entity("ISB.Models.StakeholderEngagement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_StakeholderEngagement");
                });

            modelBuilder.Entity("ISB.Models.audit_Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("buget_id")
                        .HasColumnType("int");

                    b.Property<string>("end_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kips")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("project_Status")
                        .HasColumnType("int");

                    b.Property<int>("project_id")
                        .HasColumnType("int");

                    b.Property<int>("schedule_id")
                        .HasColumnType("int");

                    b.Property<string>("start_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("buget_id");

                    b.HasIndex("project_Status");

                    b.HasIndex("project_id");

                    b.HasIndex("schedule_id");

                    b.ToTable("tbl_auditProject");
                });

            modelBuilder.Entity("ISB.Models.auditpriority", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_auditpriority");
                });

            modelBuilder.Entity("ISB.Models.client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_clients");
                });

            modelBuilder.Entity("ISB.Models.compliance_status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_compliancestatus");
                });

            modelBuilder.Entity("ISB.Models.depatement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_departments");
                });

            modelBuilder.Entity("ISB.Models.designation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("depart_id")
                        .HasColumnType("int");

                    b.Property<string>("designation_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("depart_id");

                    b.ToTable("tbl_designations");
                });

            modelBuilder.Entity("ISB.Models.emp_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_emptypes");
                });

            modelBuilder.Entity("ISB.Models.employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("depart_id")
                        .HasColumnType("int");

                    b.Property<int>("designationid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("email_Notification")
                        .HasColumnType("int");

                    b.Property<string>("emplyoment_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iamge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("joining_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("login_allowed")
                        .HasColumnType("int");

                    b.Property<string>("marital_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<string>("salutation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("depart_id");

                    b.HasIndex("designationid");

                    b.HasIndex("role_id");

                    b.ToTable("tbl_employee");
                });

            modelBuilder.Entity("ISB.Models.maritalStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_maritalstatus");
                });

            modelBuilder.Entity("ISB.Models.project", b =>
                {
                    b.Property<int>("Project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Project_id"));

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("end_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("project_priority")
                        .HasColumnType("int");

                    b.Property<int>("project_statuss")
                        .HasColumnType("int");

                    b.Property<int>("project_types")
                        .HasColumnType("int");

                    b.Property<string>("start_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("team_id")
                        .HasColumnType("int");

                    b.Property<int?>("teamid")
                        .HasColumnType("int");

                    b.HasKey("Project_id");

                    b.HasIndex("client_id");

                    b.HasIndex("project_priority");

                    b.HasIndex("project_statuss");

                    b.HasIndex("project_types");

                    b.HasIndex("team_id");

                    b.HasIndex("teamid");

                    b.ToTable("tbl_projects");
                });

            modelBuilder.Entity("ISB.Models.project_priority", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_projectpriority");
                });

            modelBuilder.Entity("ISB.Models.project_status", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<string>("colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("status_id");

                    b.ToTable("tbl_projectStatus");
                });

            modelBuilder.Entity("ISB.Models.project_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_typeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_project_types");
                });

            modelBuilder.Entity("ISB.Models.risk", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Risk_factor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("impact_risk")
                        .HasColumnType("int");

                    b.Property<int>("likelihood_risk")
                        .HasColumnType("int");

                    b.Property<string>("risk_category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_scoring")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_risks");
                });

            modelBuilder.Entity("ISB.Models.risk_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_risk_types");
                });

            modelBuilder.Entity("ISB.Models.riskmangament", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Effectiveness_id")
                        .HasColumnType("int");

                    b.Property<string>("IdentifiedRisks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likelihood")
                        .HasColumnType("int");

                    b.Property<string>("Risk_Mitigation_Plans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risk_Scoring")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stakeholder_id")
                        .HasColumnType("int");

                    b.Property<string>("impact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Effectiveness_id");

                    b.HasIndex("Stakeholder_id");

                    b.ToTable("tbl_riskmangament");
                });

            modelBuilder.Entity("ISB.Models.roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("roles_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_roles");
                });

            modelBuilder.Entity("ISB.Models.sub_task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.Property<string>("files_upload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("risk_id")
                        .HasColumnType("int");

                    b.Property<string>("start_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("task_id")
                        .HasColumnType("int");

                    b.Property<string>("tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("emp_id");

                    b.HasIndex("risk_id");

                    b.HasIndex("task_id");

                    b.ToTable("tbl_subtask");
                });

            modelBuilder.Entity("ISB.Models.survey", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descriptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("emp_id");

                    b.ToTable("tbl_survey");
                });

            modelBuilder.Entity("ISB.Models.task", b =>
                {
                    b.Property<int>("task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("task_id"));

                    b.Property<string>("created_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employee_ids")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("project_")
                        .HasColumnType("int");

                    b.Property<int?>("riskid")
                        .HasColumnType("int");

                    b.Property<int>("task_priority")
                        .HasColumnType("int");

                    b.Property<int>("task_statuss")
                        .HasColumnType("int");

                    b.Property<int>("task_types")
                        .HasColumnType("int");

                    b.Property<string>("updated_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("task_id");

                    b.HasIndex("employee_ids");

                    b.HasIndex("project_");

                    b.HasIndex("riskid");

                    b.HasIndex("task_priority");

                    b.HasIndex("task_statuss");

                    b.HasIndex("task_types");

                    b.ToTable("tbl_tasks");
                });

            modelBuilder.Entity("ISB.Models.task_files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("task_ids")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_taks_file");
                });

            modelBuilder.Entity("ISB.Models.task_priority", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_taskpriority");
                });

            modelBuilder.Entity("ISB.Models.task_status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_task_status");
                });

            modelBuilder.Entity("ISB.Models.task_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tbl_task_types");
                });

            modelBuilder.Entity("ISB.Models.team", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("team_des")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_leader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_member1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_member2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_member3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_member4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_member5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_member6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_teams");
                });

            modelBuilder.Entity("ISB.Models.Audit", b =>
                {
                    b.HasOne("ISB.Models.auditpriority", "priorityDetails")
                        .WithMany("auditdetails")
                        .HasForeignKey("Priority_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.AuditType", "typesDetails")
                        .WithMany("auditdetails")
                        .HasForeignKey("Type_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.employee", "empDetails")
                        .WithMany("audit_details")
                        .HasForeignKey("assignedauditor")
                        .IsRequired();

                    b.HasOne("ISB.Models.project", "projectDetails")
                        .WithMany("audit_details")
                        .HasForeignKey("project_id")
                        .IsRequired();

                    b.Navigation("empDetails");

                    b.Navigation("priorityDetails");

                    b.Navigation("projectDetails");

                    b.Navigation("typesDetails");
                });

            modelBuilder.Entity("ISB.Models.Audit_Conclusion", b =>
                {
                    b.HasOne("ISB.Models.Audit_Rating", "_Rating")
                        .WithMany("conclusions")
                        .HasForeignKey("rating_id")
                        .IsRequired();

                    b.Navigation("_Rating");
                });

            modelBuilder.Entity("ISB.Models.ComplianceStandards", b =>
                {
                    b.HasOne("ISB.Models.compliance_status", "status")
                        .WithMany("standards")
                        .HasForeignKey("compliacne_id")
                        .IsRequired();

                    b.Navigation("status");
                });

            modelBuilder.Entity("ISB.Models.CorrectiveMeasures", b =>
                {
                    b.HasOne("ISB.Models.CorrectiveMeasures_priority", "priority")
                        .WithMany("CorrectiveMeasures")
                        .HasForeignKey("priority_id")
                        .IsRequired();

                    b.Navigation("priority");
                });

            modelBuilder.Entity("ISB.Models.audit_Project", b =>
                {
                    b.HasOne("ISB.Models.BudgetAdherence", "budgetdetails")
                        .WithMany("auditproject_details")
                        .HasForeignKey("buget_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.project_status", "projectStatus")
                        .WithMany("auditproject_details")
                        .HasForeignKey("project_Status")
                        .IsRequired();

                    b.HasOne("ISB.Models.project", "project")
                        .WithMany("audit_projectdetails")
                        .HasForeignKey("project_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.ScheduleAdherence", "scheduledetails")
                        .WithMany("auditproject_details")
                        .HasForeignKey("schedule_id")
                        .IsRequired();

                    b.Navigation("budgetdetails");

                    b.Navigation("project");

                    b.Navigation("projectStatus");

                    b.Navigation("scheduledetails");
                });

            modelBuilder.Entity("ISB.Models.designation", b =>
                {
                    b.HasOne("ISB.Models.depatement", "depart_detail")
                        .WithMany("designation_data")
                        .HasForeignKey("depart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depart_detail");
                });

            modelBuilder.Entity("ISB.Models.employee", b =>
                {
                    b.HasOne("ISB.Models.depatement", "department_details")
                        .WithMany("employees")
                        .HasForeignKey("depart_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISB.Models.designation", "designation_details")
                        .WithMany("employees_data")
                        .HasForeignKey("designationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISB.Models.roles", "roles_details")
                        .WithMany("employees")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department_details");

                    b.Navigation("designation_details");

                    b.Navigation("roles_details");
                });

            modelBuilder.Entity("ISB.Models.project", b =>
                {
                    b.HasOne("ISB.Models.client", "client_data")
                        .WithMany("pro_details")
                        .HasForeignKey("client_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.project_priority", "priority_details")
                        .WithMany("project_details")
                        .HasForeignKey("project_priority")
                        .IsRequired();

                    b.HasOne("ISB.Models.project_status", "status_details")
                        .WithMany("project_details")
                        .HasForeignKey("project_statuss")
                        .IsRequired();

                    b.HasOne("ISB.Models.project_type", "types_details")
                        .WithMany("project_details")
                        .HasForeignKey("project_types")
                        .IsRequired();

                    b.HasOne("ISB.Models.employee", "employee_details")
                        .WithMany("project_details")
                        .HasForeignKey("team_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.team", null)
                        .WithMany("pro_details")
                        .HasForeignKey("teamid");

                    b.Navigation("client_data");

                    b.Navigation("employee_details");

                    b.Navigation("priority_details");

                    b.Navigation("status_details");

                    b.Navigation("types_details");
                });

            modelBuilder.Entity("ISB.Models.riskmangament", b =>
                {
                    b.HasOne("ISB.Models.Communication_Effectivenes", "Effectiveness_Engagement")
                        .WithMany("riskmangaments")
                        .HasForeignKey("Effectiveness_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.StakeholderEngagement", "Stakeholder_Engagement")
                        .WithMany("riskmangaments")
                        .HasForeignKey("Stakeholder_id")
                        .IsRequired();

                    b.Navigation("Effectiveness_Engagement");

                    b.Navigation("Stakeholder_Engagement");
                });

            modelBuilder.Entity("ISB.Models.sub_task", b =>
                {
                    b.HasOne("ISB.Models.employee", "emp_details")
                        .WithMany("subtasks_details")
                        .HasForeignKey("emp_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.risk", "risl_details")
                        .WithMany("subtasks_details")
                        .HasForeignKey("risk_id")
                        .IsRequired();

                    b.HasOne("ISB.Models.task", "task_details")
                        .WithMany("subtasks_details")
                        .HasForeignKey("task_id")
                        .IsRequired();

                    b.Navigation("emp_details");

                    b.Navigation("risl_details");

                    b.Navigation("task_details");
                });

            modelBuilder.Entity("ISB.Models.survey", b =>
                {
                    b.HasOne("ISB.Models.employee", "employee_details")
                        .WithMany("survey_details")
                        .HasForeignKey("emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee_details");
                });

            modelBuilder.Entity("ISB.Models.task", b =>
                {
                    b.HasOne("ISB.Models.employee", "emp_data")
                        .WithMany("tasks_details")
                        .HasForeignKey("employee_ids")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISB.Models.project", "project_data")
                        .WithMany("tasks_details")
                        .HasForeignKey("project_");

                    b.HasOne("ISB.Models.risk", null)
                        .WithMany("tasks_details")
                        .HasForeignKey("riskid");

                    b.HasOne("ISB.Models.task_priority", "_proprity")
                        .WithMany("tasks_details")
                        .HasForeignKey("task_priority")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISB.Models.task_status", "_status")
                        .WithMany("tasks_details")
                        .HasForeignKey("task_statuss")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISB.Models.task_type", "_types")
                        .WithMany("tasks_details")
                        .HasForeignKey("task_types")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_proprity");

                    b.Navigation("_status");

                    b.Navigation("_types");

                    b.Navigation("emp_data");

                    b.Navigation("project_data");
                });

            modelBuilder.Entity("ISB.Models.AuditType", b =>
                {
                    b.Navigation("auditdetails");
                });

            modelBuilder.Entity("ISB.Models.Audit_Rating", b =>
                {
                    b.Navigation("conclusions");
                });

            modelBuilder.Entity("ISB.Models.BudgetAdherence", b =>
                {
                    b.Navigation("auditproject_details");
                });

            modelBuilder.Entity("ISB.Models.Communication_Effectivenes", b =>
                {
                    b.Navigation("riskmangaments");
                });

            modelBuilder.Entity("ISB.Models.CorrectiveMeasures_priority", b =>
                {
                    b.Navigation("CorrectiveMeasures");
                });

            modelBuilder.Entity("ISB.Models.ScheduleAdherence", b =>
                {
                    b.Navigation("auditproject_details");
                });

            modelBuilder.Entity("ISB.Models.StakeholderEngagement", b =>
                {
                    b.Navigation("riskmangaments");
                });

            modelBuilder.Entity("ISB.Models.auditpriority", b =>
                {
                    b.Navigation("auditdetails");
                });

            modelBuilder.Entity("ISB.Models.client", b =>
                {
                    b.Navigation("pro_details");
                });

            modelBuilder.Entity("ISB.Models.compliance_status", b =>
                {
                    b.Navigation("standards");
                });

            modelBuilder.Entity("ISB.Models.depatement", b =>
                {
                    b.Navigation("designation_data");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("ISB.Models.designation", b =>
                {
                    b.Navigation("employees_data");
                });

            modelBuilder.Entity("ISB.Models.employee", b =>
                {
                    b.Navigation("audit_details");

                    b.Navigation("project_details");

                    b.Navigation("subtasks_details");

                    b.Navigation("survey_details");

                    b.Navigation("tasks_details");
                });

            modelBuilder.Entity("ISB.Models.project", b =>
                {
                    b.Navigation("audit_details");

                    b.Navigation("audit_projectdetails");

                    b.Navigation("tasks_details");
                });

            modelBuilder.Entity("ISB.Models.project_priority", b =>
                {
                    b.Navigation("project_details");
                });

            modelBuilder.Entity("ISB.Models.project_status", b =>
                {
                    b.Navigation("auditproject_details");

                    b.Navigation("project_details");
                });

            modelBuilder.Entity("ISB.Models.project_type", b =>
                {
                    b.Navigation("project_details");
                });

            modelBuilder.Entity("ISB.Models.risk", b =>
                {
                    b.Navigation("subtasks_details");

                    b.Navigation("tasks_details");
                });

            modelBuilder.Entity("ISB.Models.roles", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("ISB.Models.task", b =>
                {
                    b.Navigation("subtasks_details");
                });

            modelBuilder.Entity("ISB.Models.task_priority", b =>
                {
                    b.Navigation("tasks_details");
                });

            modelBuilder.Entity("ISB.Models.task_status", b =>
                {
                    b.Navigation("tasks_details");
                });

            modelBuilder.Entity("ISB.Models.task_type", b =>
                {
                    b.Navigation("tasks_details");
                });

            modelBuilder.Entity("ISB.Models.team", b =>
                {
                    b.Navigation("pro_details");
                });
#pragma warning restore 612, 618
        }
    }
}
